module Problem2

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
//      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.

let rec fib(n) =
    if n < 2 then
        n
    else 
        fib (n-1) + fib (n-2) 
    
let StartProblem = 
    Seq.initInfinite fib 
    |> Seq.takeWhile(fun r -> r < 4000000) 
    |> Seq.filter(fun f -> (f % 2) = 0)
    |> Seq.sum




    

   